language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
  - echo 'www.guanyuqian.com' > CNAME

after_script:
  - cd docs
  - git init
  - git config --global user.name "guanyuqian"    #gh-pages显示发布的名字
  - git config --global user.email "the_sam@foxmail.com"
  - git add .
  - git commit -m "第 $TRAVIS_BUILD_NUMBER 次上传更新我的文档"
  # Github 
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/guanyuqian/guanyuqian.github.io.git" master:gh-pages
  # Coding 
  - git push --force --quiet "${CODING_USER}:${CODING_TOKEN}@e.coding.net/guanyuqian/guanyuqian.coding.me/guanyuqian.coding.me.git" master:gh-pages
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "由TravisCI自动标记$TRAVIS_BUILD_NUMBER次"
  # Github
  - git push --quiet "https://${GITHUB_TOKEN}@github.com/guanyuqian/guanyuqian.github.io.git" master:gh-pages --tags
  # Coding
  - git push --quiet "https://${CODING_USER}:${CODING_TOKEN}@e.coding.net/guanyuqian/guanyuqian.coding.me/guanyuqian.coding.me.git" master:gh-pages --tags
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: main